version: '3.8'

services:
  # =============================================================================
  # DESPIECE-BOT - FastAPI Simple (Solo AI Stack)
  # =============================================================================
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: despiece-api
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=INFO
      - GOOGLE_AI_API_KEY=${GOOGLE_AI_API_KEY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# =============================================================================
# NETWORKS & VOLUMES
# =============================================================================
volumes:
  data_volume:
    driver: local
